[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }
SECRET_KEY = { generate = true }
